### PR TITLE
Fix osFile.ACL bug if route is nil

### LINKED ISSUE #283: Invalid memory address or nil pointer dereference
It looks like the latest release [v2.8.0](https://github.com/bep/s3deploy/compare/v2.7.0...v2.8.0) somehow broke s3deploy on a pipeline we have on circleci with the following error : 
```bash
s3deploy v2, commit none, built at unknown
iframe.html (ETag) ↑ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8b65cc]

goroutine 6 [running]:
github.com/bep/s3deploy/v2/lib.(*osFile).ACL(0xc0002da510, 0xc0004f4060, 0xc000381000)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/files.go:130 +0xc
github.com/bep/s3deploy/v2/lib.(*s3Store).Put(0xc0000d07d0, 0xaddf58, 0xc0000c5040, 0xae0408, 0xc0002da510, 0xc000402018, 0x1, 0x1, 0x0, 0xc000114e88)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/s3.go:88 +0x6d
github.com/bep/s3deploy/v2/lib.(*store).Put(0xc00018f400, 0xaddf58, 0xc0000c5040, 0xae0408, 0xc0002da510, 0xc000402018, 0x1, 0x1, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/store.go:66 +0xe7
github.com/bep/s3deploy/v2/lib.(*Deployer).upload(0xc00030e0e0, 0xaddf58, 0xc0000c5040, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/deployer.go:317 +0x1a6
github.com/bep/s3deploy/v2/lib.Deploy.func2(0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/bep/s3deploy/v2@v2.8.0/lib/deployer.go:112 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002de750, 0xc00000e3a8)
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:58 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f/errgroup/errgroup.go:55 +0x66

Exited with code exit status 2
CircleCI received exit code 2
```

We don't have any special config when it comes to s3deploy arguments : 
```bash
s3deploy -source=storybook-static/ -region=$AWS_REGION -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$AWS_BUCKET_NAME
```

Currently we downgraded to [v2.7.0](https://github.com/bep/s3deploy/releases/tag/v2.7.0) and the pipeline is back, not sure exactly what causes the problem is the newer version.

### PR DESCRIPTION
**Pull request by satotake**
Fixes #283

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this.

I do however suggests that we take another approach fixing this, which I suspect will make this less fragile in the future:

* We say that every file has a `route`, so if a file doesn't get a match in the routes set, just create one but some non nil header map and a default acl.

**Comment by bep** [comment]
I'm reverting the failing commit now, I suspect that people pull in the latest via go get, so it's better to get a fix out there sooner rather than later.

We can talk about this later, it's later here in Norway.

**Comment by satotake** [comment]
> I'm reverting the failing commit now, I suspect that people pull in the latest via go get, so it's better to get a fix out there sooner rather than later.

Agreed with it. thank you.

> We say that every file has a route, so if a file doesn't get a match in the routes set, just create one but some non nil header map and a default acl.

ok.

**Comment by satotake** [comment]
@bep 
done!
Could you check it?

**Pull request closed without merging**
